/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRouter } from "next/router";
import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
    Circle001: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013_1: THREE.Mesh;
    Plane013_2: THREE.Mesh;
    Plane013_3: THREE.Mesh;
    Plane026_1: THREE.Mesh;
    Plane026_2: THREE.Mesh;
    Plane026_3: THREE.Mesh;
    Plane026_4: THREE.Mesh;
    Plane026_5: THREE.Mesh;
    Plane026_6: THREE.Mesh;
    Plane026_7: THREE.Mesh;
    Plane026_8: THREE.Mesh;
    Circle005_1: THREE.Mesh;
    Circle005_2: THREE.Mesh;
    Plane017: THREE.Mesh;
    Circle005: THREE.Mesh;
    Plane019: THREE.Mesh;
    Plane020: THREE.Mesh;
    Plane021: THREE.Mesh;
    Plane022: THREE.Mesh;
    Plane039: THREE.Mesh;
    Plane039_1: THREE.Mesh;
    Plane024: THREE.Mesh;
    Plane025: THREE.Mesh;
    Plane026: THREE.Mesh;
    Plane027: THREE.Mesh;
    Text002: THREE.Mesh;
    Text003: THREE.Mesh;
    Text004: THREE.Mesh;
    Plane028: THREE.Mesh;
    Text005: THREE.Mesh;
    Text006: THREE.Mesh;
    Text007: THREE.Mesh;
    Text008: THREE.Mesh;
    Plane029: THREE.Mesh;
    Plane030: THREE.Mesh;
    Plane031: THREE.Mesh;
    Plane032: THREE.Mesh;
    Text009: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane034: THREE.Mesh;
    Plane035: THREE.Mesh;
    Text010: THREE.Mesh;
    Text011: THREE.Mesh;
    Text012: THREE.Mesh;
    Curve: THREE.Mesh;
    Curve001: THREE.Mesh;
    Curve002: THREE.Mesh;
  };
  materials: {
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    wire_028089177: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.024"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["SVGMat.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/3dmodelMoksha.gltf") as GLTFResult;

  const router = useRouter();

  return (
    <group {...props} dispose={null}>
      <group position={[6.65, 1.28, 6.37]} scale={0.99}>
        <pointLight
          intensity={1.9}
          decay={2}
          color="#ff8f4a"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[4.04, 1.28, 6.37]} scale={0.99}>
        <pointLight
          intensity={1.9}
          decay={2}
          color="#ff8f4a"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.87, 1.28, 6.37]} scale={0.99}>
        <pointLight
          intensity={1.9}
          decay={2}
          color="#ff8f4a"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-0.32, 1.28, 6.37]} scale={0.99}>
        <pointLight
          intensity={1.9}
          decay={2}
          color="#ff8f4a"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[3.43, -0.07, 6.78]} scale={[5.77, 7.56, 6.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[0.62, 0.36, 1.57]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[4.49, -0.07, 7.03]}
        scale={[6.76, 8.86, 6.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Material.008"]}
        position={[0.99, -0.07, 9.7]}
        scale={0.42}
      />
      <group position={[6.74, -0.07, 8.77]} scale={0.31}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_2.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[-0.84, -0.29, 2.27]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.03, 1.1, 0.87]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_3.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_4.geometry}
          material={materials.wire_028089177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_5.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_6.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_7.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026_8.geometry}
          material={materials["Material.022"]}
        />
      </group>
      <group
        position={[0.18, 0.44, 3.32]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.03}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_2.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.Material}
        position={[-0.84, -0.29, 2.27]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.03, 1.03, 0.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials.Material}
        position={[-1, 0.83, 2.71]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.1, 0.09, 0.09]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials["Material.017"]}
        position={[-0.84, -0.29, 2.27]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.03, 1.1, 0.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials.Material}
        position={[-1.05, 0.62, 3.09]}
        rotation={[0, 0.2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials["Material.003"]}
        position={[2.19, 1.41, 3.83]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials["Material.020"]}
        position={[-1.03, 1.94, 2.27]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.39}
      />
      <group position={[-1.03, 0.48, 2.27]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials["Material.001"]}
        position={[-1.03, 0.51, 2.88]}
        scale={0.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials.wire_028089177}
        position={[-1.05, 0.62, 3.09]}
        rotation={[0, 0.2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials["Material.003"]}
        position={[-0.84, -0.32, 2.27]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.03, 1.1, 0.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.Material}
        position={[1.52, 2.5, 3.8]}
        scale={0.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials.Material}
        position={[-1.02, 3.7, 1.37]}
        rotation={[1.28, 0.01, 1.51]}
        scale={0.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials.Material}
        position={[-1.21, 3.82, 1.97]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={materials.Material}
        position={[-1.04, 3.8, 2.8]}
        rotation={[1.84, 0.01, 1.62]}
        scale={0.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials["Material.001"]}
        position={[-1.03, 3.14, 2.88]}
        scale={0.05}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text005.geometry}
        material={materials.Material}
        position={[6.26, 3.2, 7.96]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.48}
        onClick={() => {
          router.push("/events");
        }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={materials.Material}
        position={[6.26, 1.65, 8.09]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text007.geometry}
        material={materials.Material}
        position={[6.26, 2.43, 10.03]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text008.geometry}
        material={materials.Material}
        position={[6.26, 0.83, 9.78]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials["Material.024"]}
        position={[5.19, -0.07, 9.22]}
        scale={0.65}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials["Material.024"]}
        position={[-1.06, -0.07, 8.86]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials["Material.024"]}
        position={[3.68, -0.07, 8.89]}
        rotation={[Math.PI, -0.89, Math.PI]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials["Material.024"]}
        position={[3.76, -0.07, 10.36]}
        rotation={[Math.PI, -1.19, Math.PI]}
        scale={0.2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text009.geometry}
        material={materials.Material}
        position={[-1.03, 0.42, 1.84]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials["Material.023"]}
        position={[-0.84, -0.33, 2.27]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials["Material.023"]}
        position={[1.52, 2.73, 3.82]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials["Material.003"]}
        position={[0.01, 3.09, 3.8]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text010.geometry}
        material={nodes.Text010.material}
        position={[6.65, 0.82, 3.57]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text011.geometry}
        material={nodes.Text011.material}
        position={[6.65, 0.82, 1.45]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text012.geometry}
        material={materials.Material}
        position={[6.65, 0.85, 2.63]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials["Material.016"]}
        position={[7.58, 0.5, 5.89]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={24.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials["Material.018"]}
        position={[7.58, 0.5, 5.89]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={24.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        material={materials["SVGMat.002"]}
        position={[-0.8, 2.81, 2.26]}
        rotation={[Math.PI / 2, -0.26, Math.PI / 2]}
        scale={3.17}
      />
    </group>
  );
}

useGLTF.preload("/3dmodelMoksha.gltf");

export default Model;
